### ISSUE TITLE
Command for constructing the data folder

### ISSUE THREAD

**Issue by SongDoHou** [ybgdgh/Co-NavGPT#2]
Hi, thank you for your work, I really appreciate it.

Could you provide me the command for downloading the dataset as mentioned in "[Setting up datasets](https://github.com/ybgdgh/Co-NavGPT#:~:text=r%20requirements.txt-,Setting%20up%20datasets,-The%20code%20requires)"?

or can you provide some detail instructions for constructing them?

**Comment by ybgdgh** [comment]
Hi, you can just follow the [command ](https://github.com/ybgdgh/Co-NavGPT?tab=readme-ov-file#habitat-matterport) to get the HM3D dataset and scene dataset, which is the same setting as habitat-lab repo. Then you can keep the same file tree as the setting up datasets shown.
