### ISSUE TITLE
the version of numpy and scikit-fmm

### ISSUE THREAD

**Issue by BigTree765** [ybgdgh/Co-NavGPT#4]
When I try to install scikit-fmm==2019.1.30 using 'pip', I encounter an issue. I suspect this may be due to the version of numpy. The numpy version in my environment is 1.26.3, which was automatically installed when I installed torchv1.12.1. Can you please provide the recommended version of numpy?"

the error is :
![image](https://github.com/ybgdgh/Co-NavGPT/assets/44998403/d36b71ba-bae3-451a-8294-11a8afd15c18)

**Comment by ybgdgh** [comment]
Thanks for your interest. The numpy version i used is 1.22.3, you can update the scikit-fmm to 2023.4.2. Hope this can help you.

**Comment by yusirhhh** [comment]
Thank you for your response. I resolved the issue by updating scikit-fmm to version 2023.4.2. I downloaded the dataset using the following commands.  

I downloaded the dataset using the following commands:
```python
  python -m habitat_sim.utils.datasets_download –username xxx --password xxx  --uids hm3d_val_v0.2
  python -m habitat_sim.utils.datasets_download –username xxx --password xxx  --uids hm3d_train_v0.2
```
However, when I run the code (python exp_main_gpt.py), I encounter the following issue:
```python
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets/objectnav_hm3d_v2/val/val.json.gz'
```
My data folder is structured as follows:
![image](https://github.com/ybgdgh/Co-NavGPT/assets/44998403/062d521c-6c43-40b8-8d89-5f10e991727b)

In contrast, the recommended data folder structure is:
```python
objectgoal_hm3d/
        train/
        val/
        val_mini/
```
I'm unsure whether 'val-habitat-files.json' is equivalent to 'val.json.gz'. Could you provide clarification on this matter?"

**Comment by BigTree765** [comment]
Thank you for your prompt response. I have resolved the issue by downloading scikit-fmm version 2023.4.2.
